NZ.Railways/Models/BookingDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NZ.Railways.Models
{
    public class BookingDto
    {
        [Required(ErrorMessage = "* A valid departure city is required.")]
        [StringLength(5, MinimumLength = 1, ErrorMessage = "* A valid departure city is required.")]
        public string StartStation { get; set; }

        [Required(ErrorMessage = "* A valid arrival city is required.")]
        [StringLength(5, MinimumLength = 1, ErrorMessage = "* A valid arrival city required.")]
        public string EndStation { get; set; }
    }
}

NZ.Railways/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NZ.Railways.Models;

namespace NZ.Railways.Controllers
{
    public class BookingController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: Booking
        [HttpGet]
        public ActionResult BookTickets()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SearchTicket(BookingDto booking)
        {
            if (ModelState.IsValid)
            {
                //do algoritham
                //create kind of helper class or kind of BookingFacade.
                ViewBag.totaldistance = "200";
                ModelState.Clear();
            }
            return View("BookTickets");
        }
        

    }
}

NZ.Railways/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NZ.Railways.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NZ.Railways/Views/Booking/BookTickets.cshtml
@model NZ.Railways.Models.BookingDto

@{
    ViewBag.Title = "BookTickets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("SearchTicket","Booking")) 
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <div class="ticket-container">
                <div class="row m-l-1">
                    <h4 class="text-primary"><strong>Get Tickets</strong></h4>
                </div>
                <div class="row m-l-1">
                    @Html.EditorFor(model => model.StartStation, new {htmlAttributes = new {@class = "input-lg margin-bottom"}})
                    @Html.ValidationMessageFor(model => model.StartStation, "", new {@class = "p-l-1 text-danger"})
                </div>
                <div class="row m-l-1">
                    @Html.EditorFor(model => model.EndStation, new {htmlAttributes = new {@class = "input-lg margin-bottom"}})
                    @Html.ValidationMessageFor(model => model.EndStation, "", new {@class = "p-l-1  text-danger"})
                </div>
                <div class="row pull-right m-r-1">
                    <input type="submit" value="Search and Book" class="btn btn-success btn-lg margin-bottom"/>
                </div>

                @if (ViewBag.totaldistance != null){
                    <div class="row m-l-1">
                        <span class="text-primary">Total Distance : @ViewBag.totaldistance</span>
                    </div>
                }
                
                </div>

        </div>
    </div>

           
            }

NZ.Railways/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NZ.Railways/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NZ.Railways/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NZ.Railways/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("Booking", "BookTickets", "Booking")</li>
            </ul>
        </div>
    </div>
</div>
<div class="header-container">
    
</div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>